### PR TITLE
update to 1.12.2

### PR DESCRIPTION
**Pull request by asiekierka**
shhhhhhh

### CODE REVIEW

**Comment by asiekierka** [comment]
Is anything going to happen regarding this port, or should I consider maintaining a fork instead?

**Comment by kihira** [comment]
So found out why I didn't get notification of this, turns out I was not watching my own repository. If you wish to take ownership of this project instead, you can go ahead as I don't have a ton of time unfortunately. Otherwise I'll merge this up and release it :)

**Comment by asiekierka** [comment]
I mean, I'm not going to do much with it beyond updating (I'll admit, the only reason I ported it is because a friend's modpack had both Immersive Engineering and Tails, but somehow not this wonder of the modding world) as I'm not a huge fan of IE myself.

I think the best bet is for you to merge it up and release it.

**Comment by kihira** [comment]
Gotcha, and thank you very much :D I'll release this tonight hopefully

**Pull request merged**
